crashcourse/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import (
    LoginView,
    LogoutView,
)

from todo.views import signupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', signupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', include('todo.urls', namespace='todos'))
]

todo/urls.py
from django.urls import path
from .views import (
    todo_detail, 
    todo_list, 
    todo_create, 
    todo_update, 
    todo_delete
) 

app_name = 'todos'

urlpatterns = [
    # path('', todo_list, name="home"), function url
    path('', todo_list.as_view(), name="home"), #class url

    # path('create/', todo_create), #function url
    path('create/', todo_create.as_view()),

    # path('<id>/', todo_detail), function url
    path('<str:pk>/', todo_detail.as_view()), #class url


    # path('<id>/update', todo_update),

    path('<id>/delete', todo_delete), 
    path('<str:pk>/update', todo_update.as_view(), name="update"), #class url
]

todo/models.py
from django.db import models
from django.db.models import aggregates
from django.shortcuts import render
from django.db import models

class Todo(models.Model):
    Name = models.CharField(max_length=100)
    Due_Date = models.DateField()

    def __str__(self):
        return self.Name

class personal_info(models.Model):
    First_Name = models.CharField(max_length=50)
    Last_Name = models.CharField(max_length=50)
    age = models.IntegerField(default=15)
    job = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.First_Name} {self.Last_Name}'

todo/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render, reverse
from .models import Todo
from .form import TodoForm, userform

from django.views import generic

# def todo_list(request):
#     todos = Todo.objects.all()
#     print(todos)
#     context = {
#         "todo_list": todos
#     }
#     return render(request, "todo/todo_list_inner.html", context)

# classbase version of todo_list
# class todo_list(generic.TemplateView):
#     template_name = "todo/todo_list_inner.html"

class todo_list(generic.ListView):
    template_name = 'todo/todo_list_inner.html'
    context_object_name = 'todo_list'

    def get_queryset(self):
        queryset = Todo.objects.all()
        return queryset

# def todo_detail(request, id):
#     todo = Todo.objects.get(id=id)
#     context = {
#         "todo" : todo
#     }
#     return render(request, "todo/todo_detail.html", context)

class todo_detail(generic.DetailView):
    template_name = 'todo/todo_detail.html'
    queryset = Todo.objects.all()
    context_object_name = "todo"


# def todo_create(request):
#     form = TodoForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         return redirect('/')
#         # print(form.cleaned_data)
#         pass
#     context = {
#         "form" : form
#     }
#     return render(request, "todo/todo_create.html", context)

class todo_create(generic.CreateView):
    template_name = 'todo/todo_create.html'
    form_class = TodoForm

    def get_success_url(self):
        return reverse("todo:home")


# def todo_update(request, id):
#     todo = Todo.objects.get(id=id)
#     form = TodoForm(request.POST or None, instance=todo)
#     if form.is_valid():
#         form.save()
#         return redirect('/')

#     context = { "form": form }
#     return render(request, "todo/todo_update.html", context)

class todo_update(generic.UpdateView):
    template_name = 'todo/todo_update.html'
    form_class = TodoForm
    queryset = Todo.objects.all()

    def get_success_url(self):
        return reverse("todos:home")

def todo_delete(request, id):
    todo = Todo.objects.get(id=id)
    todo.delete()

    return redirect('/')

class signupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = userform

    def get_success_url(self):
        return reverse("login")

todo/templates/todo/todo_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django crash course</title>
</head>
<body>
    <h1>Create Todo</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>Submit</button>
    </form>
</body>
</html>

todo/templates/todo/todo_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django crash course</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <h1>Welcome {{ request.user.username }}</h1>
    {% else %}
        <h1>Welcome Anonymous user</h1>
    {% endif %}

    The todo name is: {{ todo.Name }} <br>
    The due date is: {{ todo.Due_Date }}
<!-- 
    <p><a href="/{{ todo.id }} /update">Update Todo</a></p>
    <p><a href="/{{ todo.id }} /delete">Delete Todo</a></p> -->

    <p> <a href="{% url 'todos:update' todo.pk %}"> update</a></p>


</body>
</html>

todo/templates/todo/todo_list_inner.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django crash course</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <h1>Welcome {{ request.user.username }}</h1>
    {% else %}
        <h1>Welcome Anonymous user</h1>
    {% endif %}
    <a style="display: block; margin-bottom: 2rem;" href=" {% url 'logout' %} "><button>Logout</button></a>

    <a href="/create">Create a todo list"</a>
    
    {% for todo in todo_list %}
    <ul>
        <li>
            Todo Item: <a href="/{{ todo.id }}"> {{ todo.Name }} </a>
        </li>
        <h6>Due Date: {{ todo.Due_Date }}</h6>
    </ul>
    {% endfor %}
</body>
</html>

todo/templates/todo/todo_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django crash course</title>
</head>
<body>
    <h1>Update Todo</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>Submit</button>
    </form>
</body>
</html>